const studentActionTypes = {
  LOGIN_IN_START: 'LOGIN_IN_START',
  LOGIN_IN_SUCCESS: 'LOGIN_IN_SUCCESS',
  LOGIN_IN_FAILURE: 'LOGIN_IN_FAILURE',
  CREATE_STUDENT_START: 'CREATE_STUDENT_START',
  CREATE_STUDENT_SUCCESS: 'CREATE_STUDENT_SUCCESS',
  CREATE_STUDENT_FAILURE: 'CREATE_STUDENT_FAILURE',
};

export default studentActionTypes;
