const subjectActionTypes = {
  SUBJECTS_FETCH_REQUEST: 'SUBJECTS_FETCH_REQUEST',
  SUBJECTS_FETCH_SUCCESS: 'SUBJECTS_FETCH_SUCCESS',
  SUBJECTS_FETCH_FAILURE: 'SUBJECTS_FETCH_FAILURE',
};

export default subjectActionTypes;
