const subjectActionTypes = {
  SUBJECTS_FETCH_REQUEST: 'SUBJECTS_FETCH_REQUEST',
  SUBJECTS_FETCH_SUCCESS: 'SUBJECTS_FETCH_SUCCESS',
  SUBJECTS_FETCH_FAILURE: 'SUBJECTS_FETCH_FAILURE',
  CREATE_SUBJECT_START: 'CREATE_SUBJECT_START',
  CREATE_SUBJECT_SUCCESS: 'CREATE_SUBJECT_SUCCESS',
  CREATE_SUBJECT_FAILURE: 'CREATE_SUBJECT_FAILURE',
};

export default subjectActionTypes;
