const clockingActionTypes = {
  CLOCKINGS_FETCH_REQUEST: 'CLOCKINGS_FETCH_REQUEST',
  CLOCKINGS_FETCH_SUCCESS: 'CLOCKINGS_FETCH_SUCCESS',
  CLOCKINGS_FETCH_FAILURE: 'CLOCKINGS_FETCH_FAILURE',
};

export default clockingActionTypes;
