const clockingActionTypes = {
  CLOCKINGS_FETCH_REQUEST: 'CLOCKINGS_FETCH_REQUEST',
  CLOCKINGS_FETCH_SUCCESS: 'CLOCKINGS_FETCH_SUCCESS',
  CLOCKINGS_FETCH_FAILURE: 'CLOCKINGS_FETCH_FAILURE',
  CREATE_CLOCKING_START: 'CREATE_CLOCKING_START',
  CREATE_CLOCKING_SUCCESS: 'CREATE_CLOCKING_SUCCESS',
  CREATE_CLOCKING_FAILURE: 'CREATE_CLOCKING_FAILURE',
  DELETE_CLOCKING_START: 'DELETE_CLOCKING_START',
  DELETE_CLOCKING_SUCCESS: 'DELETE_CLOCKING_SUCCESS',
  DELETE_CLOCKING_FAILURE: 'DELETE_CLOCKING_FAILURE',
  EDIT_CLOCKING_START: 'EDIT_CLOCKING_START',
  EDIT_CLOCKING_SUCCESS: 'EDIT_CLOCKING_SUCCESS',
  EDIT_CLOCKING_FAILURE: 'EDIT_CLOCKING_FAILURE',
};

export default clockingActionTypes;
